//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmerTest1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Users\\Leanid\\Dropbox\\Alarmer")]
        public string HomeAlarmListPath {
            get {
                return ((string)(this["HomeAlarmListPath"]));
            }
            set {
                this["HomeAlarmListPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlarmListOffice.txt")]
        public string OfficeListName {
            get {
                return ((string)(this["OfficeListName"]));
            }
            set {
                this["OfficeListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlarmListHome.txt")]
        public string HomeListName {
            get {
                return ((string)(this["HomeListName"]));
            }
            set {
                this["HomeListName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dataForHome.")]
        public string DataForHome {
            get {
                return ((string)(this["DataForHome"]));
            }
            set {
                this["DataForHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dataForOffice.")]
        public string DataForOffice {
            get {
                return ((string)(this["DataForOffice"]));
            }
            set {
                this["DataForOffice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("permissionForOffice.")]
        public string PermissionForOffice {
            get {
                return ((string)(this["PermissionForOffice"]));
            }
            set {
                this["PermissionForOffice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("permissionForHome.")]
        public string PermissionForHome {
            get {
                return ((string)(this["PermissionForHome"]));
            }
            set {
                this["PermissionForHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Users\\mli2805\\Dropbox\\Alarmer")]
        public string OfficeAlarmListPath {
            get {
                return ((string)(this["OfficeAlarmListPath"]));
            }
            set {
                this["OfficeAlarmListPath"] = value;
            }
        }
    }
}
